{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ include "address-picker.namespace" . }}
  labels:
    {{- include "address-picker.labels" . | nindent 4 }}
    component: api
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "address-picker.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "address-picker.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- if .Values.dockerSecret.create }}
      imagePullSecrets:
        - name: {{ .Values.dockerSecret.name }}
      {{- end }}
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ include "address-picker.backend.image" . }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
          protocol: TCP
        env:
        {{- range .Values.backend.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        {{- if .Values.backend.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.backend.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}
        {{- end }}
{{- end }}
