{{- if .Values.dockerSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerSecret.name }}
  namespace: {{ include "address-picker.namespace" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "{{ .Values.dockerSecret.auth }}"
        }
      }
    }
{{- end }}