{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ include "address-picker.namespace" . }}
  labels:
    {{- include "address-picker.labels" . | nindent 4 }}
    component: web
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "address-picker.selectorLabels" . | nindent 6 }}
      component: web
  template:
    metadata:
      labels:
        {{- include "address-picker.selectorLabels" . | nindent 8 }}
        component: web
    spec:
      {{- if .Values.dockerSecret.create }}
      imagePullSecrets:
        - name: {{ .Values.dockerSecret.name }}
      {{- end }}
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ include "address-picker.frontend.image" . }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
          name: http
          protocol: TCP
        env:
        {{- range .Values.frontend.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        {{- if .Values.frontend.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.frontend.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
        {{- end }}
{{- end }}
