{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "address-picker.namespace" . }}
  labels:
    {{- include "address-picker.labels" . | nindent 4 }}
    name: {{ include "address-picker.namespace" . }}
{{- end }}
